function t199_showMenu(recid){var el=$("#rec"+recid);el.find('.t199__js__menu').each(function(){var $toggler=el.find('.t199__js__menu-toggler'),$menu=$(this),$body=$('body'),CLASS_MENU='t199__is__menu';$menu.find('.t199__menu-item').each(function(){var curUrl=$(this).attr('href');if(typeof curUrl!='undefined'&&curUrl.indexOf('#')>-1&&curUrl.substring(0,9)!='#submenu:'){$(this).on('click',function(e){$body.removeClass(CLASS_MENU)})}});$toggler.on('click',function(e){e.stopPropagation();e.preventDefault();$body.toggleClass(CLASS_MENU)});$(document).on('click',function(){$body.removeClass(CLASS_MENU)});$menu.on('click',function(e){e.stopPropagation()})})
$('.t199__mmenu').bind('clickedAnchorInTooltipMenu',function(){$('body').removeClass('t199__is__menu')})}
function t199_positionHeader(recid){var el=$("#rec"+recid);var $header=el.find('.t199__js__header'),isScrolling=!1,CLASS_ACTIVE='t199__is__active';function updateHeader(){isScrolling=!0;if($(window).scrollTop()>0)$header.addClass(CLASS_ACTIVE);else $header.removeClass(CLASS_ACTIVE)}
setInterval(function(){if(isScrolling){isScrolling=!1}},100);$(window).on('scroll',updateHeader)
updateHeader()}
function t199_setPath(pageid){}
function t199_highlight(recid){var url=window.location.href;var pathname=window.location.pathname;if(url.substr(url.length-1)=="/"){url=url.slice(0,-1)}
if(pathname.substr(pathname.length-1)=="/"){pathname=pathname.slice(0,-1)}
if(pathname.charAt(0)=="/"){pathname=pathname.slice(1)}
if(pathname==""){pathname="/"}
$(".t199__menu a[href='"+url+"']").addClass("t-active");$(".t199__menu a[href='"+url+"/']").addClass("t-active");$(".t199__menu a[href='"+pathname+"']").addClass("t-active");$(".t199__menu a[href='/"+pathname+"']").addClass("t-active");$(".t199__menu a[href='"+pathname+"/']").addClass("t-active");$(".t199__menu a[href='/"+pathname+"/']").addClass("t-active")}
function t199_checkAnchorLinks(recid){if($(window).width()>=960){var t199_navLinks=$("#rec"+recid+" .t-menu__link-item:not(.tooltipstered)[href*='#']");if(t199_navLinks.length>0){t199_catchScroll(t199_navLinks)}}}
function t199_catchScroll(t199_navLinks){var t199_clickedSectionId=null,t199_sections=new Array(),t199_sectionIdTonavigationLink=[],t199_interval=100,t199_lastCall,t199_timeoutId;t199_navLinks=$(t199_navLinks.get().reverse());t199_navLinks.each(function(){var t199_cursection=t199_getSectionByHref($(this));if(typeof t199_cursection.attr("id")!="undefined"){t199_sections.push(t199_cursection)}
t199_sectionIdTonavigationLink[t199_cursection.attr("id")]=$(this)});t199_updateSectionsOffsets(t199_sections);$(window).bind('resize',t_throttle(function(){t199_updateSectionsOffsets(t199_sections)},200));$('.t199').bind('displayChanged',function(){t199_updateSectionsOffsets(t199_sections)});setInterval(function(){t199_updateSectionsOffsets(t199_sections)},5000);t199_highlightNavLinks(t199_navLinks,t199_sections,t199_sectionIdTonavigationLink,t199_clickedSectionId);t199_navLinks.click(function(){if(!$(this).hasClass("tooltipstered")){t199_navLinks.removeClass('t-active');t199_sectionIdTonavigationLink[t199_getSectionByHref($(this)).attr("id")].addClass('t-active');t199_clickedSectionId=t199_getSectionByHref($(this)).attr("id")}});$(window).scroll(function(){var t199_now=new Date().getTime();if(t199_lastCall&&t199_now<(t199_lastCall+t199_interval)){clearTimeout(t199_timeoutId);t199_timeoutId=setTimeout(function(){t199_lastCall=t199_now;t199_clickedSectionId=t199_highlightNavLinks(t199_navLinks,t199_sections,t199_sectionIdTonavigationLink,t199_clickedSectionId)},t199_interval-(t199_now-t199_lastCall))}else{t199_lastCall=t199_now;t199_clickedSectionId=t199_highlightNavLinks(t199_navLinks,t199_sections,t199_sectionIdTonavigationLink,t199_clickedSectionId)}})}
function t199_updateSectionsOffsets(sections){$(sections).each(function(){var t199_curSection=$(this);t199_curSection.attr("data-offset-top",t199_curSection.offset().top)})}
function t199_getSectionByHref(curlink){var t199_curLinkValue=curlink.attr("href").replace(/\s+/g,'');if(curlink.is('[href*="#rec"]')){return $(".r[id='"+t199_curLinkValue.substring(1)+"']")}else{return $(".r[data-record-type='215']").has("a[name='"+t199_curLinkValue.substring(1)+"']")}}
function t199_highlightNavLinks(t199_navLinks,t199_sections,t199_sectionIdTonavigationLink,t199_clickedSectionId){var t199_scrollPosition=$(window).scrollTop(),t199_valueToReturn=t199_clickedSectionId;if(t199_sections.length!=0&&t199_clickedSectionId==null&&t199_sections[t199_sections.length-1].attr("data-offset-top")>(t199_scrollPosition+300)){t199_navLinks.removeClass('t-active');return null}
$(t199_sections).each(function(e){var t199_curSection=$(this),t199_sectionTop=t199_curSection.attr("data-offset-top"),t199_id=t199_curSection.attr('id'),t199_navLink=t199_sectionIdTonavigationLink[t199_id];if(((t199_scrollPosition+300)>=t199_sectionTop)||(t199_sections[0].attr("id")==t199_id&&t199_scrollPosition>=$(document).height()-$(window).height())){if(t199_clickedSectionId==null&&!t199_navLink.hasClass('t-active')){t199_navLinks.removeClass('t-active');t199_navLink.addClass('t-active');t199_valueToReturn=null}else{if(t199_clickedSectionId!=null&&t199_id==t199_clickedSectionId){t199_valueToReturn=null}}
return!1}});return t199_valueToReturn}
function t397_init(recid){var el=$('#rec'+recid);el.find('.t397__tab').click(function(){el.find('.t397__tab').removeClass('t397__tab_active');$(this).addClass('t397__tab_active');t397_alltabs_updateContent(recid);t397_updateSelect(recid);$('.t230, .t670, .t347, .t346, .t519, .t774, .t764, .t744, .t349, .t650, .t604, .t117, .t517, .t609, .t351, .t353, .t341, .t404, .t385, .t386, .t412, .t268, .t425, .t409, .t384, .t279, .t428, .t418, .t433, .t121, .t478, .t498, .t552, .t544, .t554, .t545, .t486, .t570, .t422, .t601, .t228, .t229, .t456, .t592, .t520, .t599, .t422, .t504, .t688, .t675, .t132, .t616, .t686, .t778, .t615, .t433, .t598, .t762, .t538, .t226, .t698, .t760, .t511, .t799, .t780, .t827, .t740, .t480, .t827, .t829, .t605, .t726, .t728, .t822, .t798, .t801, .t694, .t842, .t843, .t849, .t850, .t851, .t856, .t858, .t859, .t860, .t396, .t518, .t738, .t532').trigger('displayChanged');setTimeout(function(){$('.t351, .t353, .t341, .t404, .t385, .t386, .t412, .t268, .t425, .t409, .t384, .t279, .t428, .t433, .t545, .t422, .t410, .t829, .t396, .t738').trigger('displayChanged')},50);if(window.lazy=='y'){t_lazyload_update()}});t397_alltabs_updateContent(recid);t397_updateContentBySelect(recid);$('.t397').bind('displayChanged',function(){t397_alltabs_updateContent(recid);t397_updateContentBySelect(recid)});var bgcolor=el.css("background-color");var bgcolor_target=el.find(".t397__select, .t397__firefoxfix");bgcolor_target.css("background-color",bgcolor)}
function t397_alltabs_updateContent(recid){var el=$('#rec'+recid);el.find(".t397__tab").each(function(i){var rec_ids=$(this).attr('data-tab-rec-ids').split(',');rec_ids.forEach(function(rec_id,i,arr){var rec_el=$('#rec'+rec_id);rec_el.attr('data-connect-with-tab','yes');rec_el.attr('data-animationappear','off');rec_el.addClass('t379__off')})});el.find(".t397__tab_active").each(function(i){if($(this).is(":visible")||el.find(".t397__select").is(":visible")){var rec_ids=$(this).attr('data-tab-rec-ids').split(',');rec_ids.forEach(function(rec_id,i,arr){var rec_el=$('#rec'+rec_id);rec_el.removeClass('t379__off');rec_el.css('opacity','')})}})}
function t397_updateContentBySelect(recid){var el=$('#rec'+recid);el.find(".t397__select").change(function(){var select_val=el.find(".t397__select").val();var tab_index=el.find(".t397__tab[data-tab-rec-ids='"+select_val+"']");tab_index.trigger('click')})}
function t397_updateSelect(recid){var el=$('#rec'+recid);var current_tab=el.find(".t397__tab_active").attr('data-tab-rec-ids');var el_select=el.find(".t397__select");el_select.val(current_tab)}
function t404_unifyHeights(recid){var el=$('#rec'+recid).find(".t404");el.find('.t-container').each(function(){var highestBox=0;$('.t404__title',this).css('height','');$('.t404__title',this).each(function(){if($(this).height()>highestBox)highestBox=$(this).height()});if($(window).width()>=960){$('.t404__title',this).css('height',highestBox)}else{$('.t404__title',this).css('height',"auto")}
$('.t404__descr',this).css('height','');var highestBox=0;$('.t404__descr',this).each(function(){if($(this).height()>highestBox)highestBox=$(this).height()});if($(window).width()>=960){$('.t404__descr',this).css('height',highestBox)}else{$('.t404__descr',this).css('height',"auto")}})}
function t404_unifyHeightsTextwrapper(recid){var el=$('#rec'+recid).find(".t404");el.find('.t-container').each(function(){var highestBox=0;$('.t404__textwrapper',this).each(function(){$(this).css("height","auto");if($(this).height()>highestBox)highestBox=$(this).height()});if($(window).width()>=960){$('.t404__textwrapper',this).css('height',highestBox)}else{$('.t404__textwrapper',this).css('height',"auto")}})}
function t404_showMore(recid){var el=$('#rec'+recid).find(".t404");el.find(".t-col").hide();var cards_size=el.find(".t-col").size();var cards_count=parseInt(el.attr("data-show-count"));if(cards_count>500){cards_count=500}
var x=cards_count;var y=cards_count;el.find('.t-col:lt('+x+')').show();el.find('.t404__showmore').click(function(){x=(x+y<=cards_size)?x+y:cards_size;el.find('.t-col:lt('+x+')').show();if(x==cards_size){el.find('.t404__showmore').hide()}
$('.t404').trigger('displayChanged');if(window.lazy=='y'){t_lazyload_update()}})}
function t452_scrollToTop(){$('html, body').animate({scrollTop:0},700)}
function t712_onSuccess(t712_form){var t712_inputsWrapper=t712_form.find('.t-form__inputsbox');var t712_inputsHeight=t712_inputsWrapper.height();var t712_inputsOffset=t712_inputsWrapper.offset().top;var t712_inputsBottom=t712_inputsHeight+t712_inputsOffset;var t712_targetOffset=t712_form.find('.t-form__successbox').offset().top;if($(window).width()>960){var t712_target=t712_targetOffset-200}else{var t712_target=t712_targetOffset-100}
if(t712_targetOffset>$(window).scrollTop()||($(document).height()-t712_inputsBottom)<($(window).height()-100)){t712_inputsWrapper.addClass('t712__inputsbox_hidden');setTimeout(function(){if($(window).height()>$('.t-body').height()){$('.t-tildalabel').animate({opacity:0},50)}},300)}else{$('html, body').animate({scrollTop:t712_target},400);setTimeout(function(){t712_inputsWrapper.addClass('t712__inputsbox_hidden')},400)}
var successurl=t712_form.data('success-url');if(successurl&&successurl.length>0){setTimeout(function(){window.location.href=successurl},500)}}
function t712_fixcontentheight(id){var el=$("#rec"+id);var hcover=el.find(".t-cover").height();var hcontent=el.find("div[data-hook-content]").outerHeight();if(hcontent>300&&hcover<hcontent){var hcontent=hcontent+120;if(hcontent>1000){hcontent+=100}
console.log('auto correct cover height: '+hcontent);el.find(".t-cover").height(hcontent);el.find(".t-cover__filter").height(hcontent);el.find(".t-cover__carrier").height(hcontent);el.find(".t-cover__wrapper").height(hcontent);if($isMobile==!1){setTimeout(function(){var divvideo=el.find(".t-cover__carrier");if(divvideo.find('iframe').length>0){console.log('correct video from cover_fixcontentheight');setWidthHeightYoutubeVideo(divvideo,hcontent+'px')}},2000)}}}
function t716_onSuccess(t716_form){var t716_inputsWrapper=t716_form.find('.t-form__inputsbox');var t716_inputsHeight=t716_inputsWrapper.height();var t716_inputsOffset=t716_inputsWrapper.offset().top;var t716_inputsBottom=t716_inputsHeight+t716_inputsOffset;var t716_targetOffset=t716_form.find('.t-form__successbox').offset().top;if($(window).width()>960){var t716_target=t716_targetOffset-200}else{var t716_target=t716_targetOffset-100}
if(t716_targetOffset>$(window).scrollTop()||($(document).height()-t716_inputsBottom)<($(window).height()-100)){t716_inputsWrapper.addClass('t716__inputsbox_hidden');setTimeout(function(){if($(window).height()>$('.t-body').height()){$('.t-tildalabel').animate({opacity:0},50)}},300)}else{$('html, body').animate({scrollTop:t716_target},400);setTimeout(function(){t716_inputsWrapper.addClass('t716__inputsbox_hidden')},400)}
var successurl=t716_form.data('success-url');if(successurl&&successurl.length>0){setTimeout(function(){window.location.href=successurl},500)}}
function t716_fixcontentheight(id){var el=$("#rec"+id);var hcover=el.find(".t-cover").height();var hcontent=el.find("div[data-hook-content]").outerHeight();if(hcontent>300&&hcover<hcontent){var hcontent=hcontent+120;if(hcontent>1000){hcontent+=100}
console.log('auto correct cover height: '+hcontent);el.find(".t-cover").height(hcontent);el.find(".t-cover__filter").height(hcontent);el.find(".t-cover__carrier").height(hcontent);el.find(".t-cover__wrapper").height(hcontent);if($isMobile==!1){setTimeout(function(){var divvideo=el.find(".t-cover__carrier");if(divvideo.find('iframe').length>0){console.log('correct video from cover_fixcontentheight');setWidthHeightYoutubeVideo(divvideo,hcontent+'px')}},2000)}}}